server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pd_store?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1qw23e
  # roy添加
  rabbitmq:
    host: 192.168.64.100
    port: 5672
    username: admin
    password: admin
    virtual-host: roy-virtual-host-test   # 使用自己的空间,需要在rabbitmq服务器手动创建
  elasticsearch:
    rest:
      uris:
        - http://192.168.64.100:9200
        - http://192.168.64.100:9201
        - http://192.168.64.100:9202
mybatis:
  mapperLocations: classpath:com.pd.mapper/*.xml

logging:
  level:
    cn.tedu.ssm.mapper: debug
resources: # 指定静态资源的路径
  static-locations: classpath:/
  cache-period: 0

